services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--auth", "--keyFile", "/data/keyfile"]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pharma_user
      MONGO_INITDB_ROOT_PASSWORD: salgado
    volumes:
      - ./mongo-keyfile:/data/keyfile
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--auth", "--keyFile", "/data/keyfile"]
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pharma_user
      MONGO_INITDB_ROOT_PASSWORD: salgado
    volumes:
      - ./mongo-keyfile:/data/keyfile
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019", "--auth" , "--keyFile", "/data/keyfile"]
    ports:
      - "27019:27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pharma_user
      MONGO_INITDB_ROOT_PASSWORD: salgado
    volumes:
      - ./mongo-keyfile:/data/keyfile
      - "mongo3_data:/data/db"
      - "mongo3_config:/data/configdb"

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
