apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.6.0
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: "YOUR_FERNET_KEY"
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://user:password@postgres:5432/airflow"
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          value: "YOUR_SECRET_KEY"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: airflow-dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: airflow-dags
        hostPath:
          path: /path/to/your/airflow/dags
