name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed
  release:
    types:
      - created

jobs:
  build-and-run-dev:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

  deploy-uat:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.action == 'closed')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Inject UAT .env
        run: echo "${{ secrets.ENV_UAT }}" > .env

      - name: Source .env and export variables
        run: |
          set -a
          source .env
          set +a
      
      - name: Authenticate Docker with GCP Artifact Registry
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build and Push Docker images
        run: |
          docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/scrappers-job:latest .
          docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/scrappers-job:latest

      - name: Deploy Cloud Run Job for scrapper1
        run: |
          gcloud run jobs delete scrappers-job-scrapper1 --region=europe-west9 --quiet || true
          gcloud run jobs create scrappers-job-scrapper1 \
              --image=europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/scrappers-job:latest \
              --region=europe-west9 \
              --args "scripts.scrappers.save_sitemaps_links_to_mongo" \
              --memory=4Gi  \
              --task-timeout 24h

      - name: Execute Cloud Run Job for scrapper1
        run: |
          gcloud run jobs execute scrappers-job-scrapper1 --region=europe-west9

      - name: Deploy Cloud Run Job for scrapper2
        run: |
          gcloud run jobs delete scrappers-job-scrapper2 --region=europe-west9 --quiet || true
          gcloud run jobs create scrappers-job-scrapper2 \
              --image=europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/scrappers-job:latest \
              --region=europe-west9 \
              --args "scripts.scrappers.pharma_gdd_scraper" \
              --memory=4Gi \
              --max-retries=10

      - name: Execute Cloud Run Job for scrapper2
        run: |
          gcloud run jobs execute scrappers-job-scrapper2 --region=europe-west9
